### ISSUE TITLE
want CLI?

### ISSUE THREAD

**Issue by olstenlarck** [jonschlinkert/data-store#1]
or to do it as `data-store-cli`? it may be useful for verb and for me

/cc @jonschlinkert

**Comment by jonschlinkert** [comment]
ha, since you and others were having issues with the config values not being used correctly, I started creating one yesterday from the code that's already in verb, assemble and generate. actually... I'll push it up on verb so you can see what I'm talking about. 

 I'm open to the idea, but honestly maybe a little apprehensive to say yes since this is something I feel like I need to explore to know how it should work (for users). let me think about it a bit. of course you're more than welcome to create that lib, I think that's great.

**Comment by tunnckoCore** [comment]
ha, strange, verb wasn't marked as `watching`.

> I'll push it up on verb so you can see what I'm talking about.

Hm.. it makes more sense to be here or `data-store-cli` to be decoupled. Im guessing that it is very small and we can merge it here. And then I can use it outside of verb.

> I'm open to the idea, but honestly maybe a little apprehensive to say yes since this is something I feel like I need to explore to know how it should work (for users).

Yea yea, no prob, I'm not forcing you, lol. Basically I'm trying to make it more simple and more smaller, more general purpose - from generate and verb. It would be perfect place to test `glob-fs` implementation(s), it's limits, problems and performance. 

All that without `template` core and so much deps. verb became too large for me, but it is understandable - there should have some defaults. Actually all that around template, verb, assemble 0.6.0 is just amazing, b/c you making revolution. You expose whole template philosophy to APIs, which is awesome.

Yea your libs are pretty enough small and clear, and are inspiration for me. There's hundred ways to do one thing (even more, cuz this is js) and it's not a bad thing to try few of them.

It is just my nature to believe we always can to the things better and better, smaller and smaller, in different ways.

**Comment by jonschlinkert** [comment]
> data-store-cli

I think it makes more sense to be another lib, you can do one if you want and I'll probably use it on stuff. I just don't know if I'll use it on verb/assemble specifically yet. I don't even know what I want my own code to do for the CLI lol

>  verb became too large for me

yeah, me too. I want to move things out. Here is how I do things with big applications (this might not be obvious because it's over a longer timespan):

1. get it working
2. get it working the way a user would expect
3. optimize
4. move code that can be generalized into modules

> Yea your libs are pretty enough small and clear, and are inspiration for me

very nice of you to say, thanks for the kind words.

> It is just my nature to believe we always can do the things better and better, smaller and smaller, in different and different ways.

that's a great trait to have!

**Comment by jonschlinkert** [comment]
closing for now, we can revisit later if it comes up again

**Comment by olstenlarck** [comment]
Agree. It's pretty old.
