### ISSUE TITLE
Set Cache

### ISSUE THREAD

**Issue by plopez01** [jonschlinkert/data-store#11]
Please, it would be great to be possible to re-load the cache, or set it to something, becouse i edit the json file and the cache doesn't get updated.

**Comment by jonschlinkert** [comment]
Make sure you have the latest version of data-store, and use the API (call `.load()`) to get the store instead of node's fs methdods. Otherwise you might be trying to load the store before a write has been performed. 

Also note that there have been some changes to internals in 3.0. It sounds like you were using private properties, there is no longer a `.cache` property in 3.0.

**Comment by plopez01** [comment]
Thanks, im going to update data-store and see if works. Im using gists to download a json and set that download json to the .json file of data-store, my problem was that when i update the json, the "data" doesn't get updated until i restart my app. Let's see if updating helps.

**Comment by plopez01** [comment]
I am calling ``store.load()'' and it's not working. Let me show my code. 
``gists.download({id: 'ID of gist'}, function(err, res) {
		let finalconte = JSON.parse(conte);
		baseDatos = finalconte.files['abc.json'].content
		store.load(baseDatos);
	  });``
This code is not loading the code of the gist to the store, and I don't know why.

**Comment by doowb** [comment]
@plopez01 `store.load()` re-loads the json file into memory. It doesn't take any arguments.
If you do the following, then it will re-load the store, then update it with the new values:

```js
store.load();
store.set(baseDatos);
```

If you want to completely overwrite the file with the new data, then you can do this:

```js
// this will overwrite the entire object, then save it to the file.
store.data = baseDatos;
```

**Comment by plopez01** [comment]
Well thanks a lot!
