### ISSUE TITLE
store.clear into store.set into store.load deletes whole store

### ISSUE THREAD

**Issue by not-idol** [jonschlinkert/data-store#25]
i do :

```
    store.clear();
    store.set('players', []);
    store.load()
```

which deletes storage and only {} is left, why?

**Comment by doowb** [comment]
This is caused by the `.set` method calling `.save` which is waiting for 5 milliseconds to save to file because of the [default value](https://github.com/jonschlinkert/data-store/blob/12fb7ba4373c896d65049fc5067a22b7383b74d3/index.js#L40) for `debounce`.

When you create your `store`, pass in `{ debounce: 0 }` as a work around.
I think either the docs need to be updated to indicate that the default for `debounce` is `5` or the code needs to be updated to follow the docs which state the default for `debounce` is `undefined`

**Comment by not-idol** [comment]
hey, thanks for the fast answer! did solve my problem thanks, ill test today a bit more and then ill close this issue if i dont find anything else. thanks!
