### ISSUE TITLE
How can stored values be updated?

### ISSUE THREAD

**Issue by skeddles** [jonschlinkert/data-store#38]
Am I correct in thinking that .get() just returns the values stored in memory? If there is two separate instances of your store, how do you update them to the values stored in the file? Seems like I have to create a new instance of the store right before I run .get().

**Comment by doowb** [comment]
You can use the `.load` method to "re-load" the data from the file.

If the code your writing could potentially have multiple instances of `data-store` accessing the same file at the same time, then you should probably "wrap" `.get` and `.set` to call `.load` before those operations to ensure the data in memory is current.

```js
const store = require('data-store')({ path: process.cwd() + '/foo.json' });
const get = (...args) => {
  store.load();
  return store.get(...args);
};

const set = (...args) => {
  store.load();
  return store.set(...args);
};
```

Or you can extend the `Store` class:

```js
const { Store } = require('data-store');

class MyStore extends Store {
  get(...args) {
    this.load();
    return super.get(...args);
  }

  set(...args) {
    this.load();
    return super.set(...args);
  }

  del(...args) {
    this.load();
    return super.del(...args);
  }

  hasOwn(...args) {
    this.load();
    return super.hasOwn(...args);
  }

  clone(...args) {
    this.load();
    return super.clone(...args);
  }
}
```

Even doing that, there is still a possibility of race conditions since multiple instances are accessing the same file.
