### ISSUE TITLE
Store is not persisting

### ISSUE THREAD

**Issue by plopez01** [jonschlinkert/data-store#9]
Hi, im using this package to create a discord bot i want to save the id's of all the pepole in a server, and assign a value to each of them, there are 6800 users in the server, and store is not persisting, even if i use, store.save(); im using heroku to have my bot, and i created a folder and set the cwd there. But still dosn't work, what im doing wrong?

**Comment by jonschlinkert** [comment]
Hmm, let's try to figure out what's happening. 

A few questions:

1. Can you share a snippet of code to show your configuration for the Store? It would be useful to see how the options are passed, including the store name, cwd/path etc. 
1. Can show an example or describe more about how you're using the actual API? It would help to know, for example, if the Store API is being used directly, or if another class inheriting `Store`, etc.  This will help us rule out prototype pollution or similar causes.
1. Can you share the version of node that is being used? OS? Or any other info about the environment that might help.
1. It sounds like there isn't anything specific that is telling you what might be happening. Do you have any "hunches" or thoughts about what what's causing the bug? Anything at all that might help get us thinking?

Fwiw, I have a complete refactor of this ready to push up, I started working on it a while ago. It's possible that it will solve whatever issue you're having, simply because it's simpler and has fewer dependencies, making it easier to debug and use. 

However, it has a few breaking changes. I'll try to list them here in a bit, but I want to create this reply so you have a change to respond first. 

Thanks for brining this to our attention! It's greatly appreciated!

**Comment by plopez01** [comment]
Thanks for responding that fast!

This is my store declaration: 
`var store = require('data-store')('abc', {
	cwd: './store'
  });`
Im using node 8.11.1
Os, hmm i don't know, my bot is hosted by heroku and i deploy it using GIT.

I have this: When i start bot, the values are registred in the database, but, when i restart the bot, the values disappear, maybe git is preventing to create the store file, and is deleting it, or maybe somthing is resseting the store file.

**Comment by doowb** [comment]
@plopez01 I don't think heroku persists files across restarts so the file is probably being deleted then. You would need to save the file someplace else before the bot shuts down and restore it when the bot starts up. You could do this with S3 or even use [gists](https://github.com/jonschlinkert/gists) to keep a secret gist of the file.

**Comment by jonschlinkert** [comment]
Ah, that's it! I guess this is good news, and bad news. I didn't pay enough attention to the Heroku comment. AFAIK, heroku still does not allow data to be persisted like that. It will be deleted every time you git push. I'm not sure what the best solution would be for you, since I know very little about your use case and lots of other important factors, but now that we know what the likely cause is, I'm pretty sure there is a bunch of info on the heroku docs, stackoverflow, google about what's happening and other options.

**Comment by jonschlinkert** [comment]
ha I didn't see @doowb's comment until I saved my last one! The page didn't refresh! Looks like was a little late on that one! lol

**Comment by plopez01** [comment]
Oh, thanks a lot, im going to do it with gists. Thaks @jonschlinkert and @doowb
